import { AdvertismentCreateNestedManyWithoutSpacesInput } from "./AdvertismentCreateNestedManyWithoutSpacesInput";
import { InputJsonValue } from "../../types";
import { BookingCreateNestedManyWithoutSpacesInput } from "./BookingCreateNestedManyWithoutSpacesInput";
import { RatingCreateNestedManyWithoutSpacesInput } from "./RatingCreateNestedManyWithoutSpacesInput";
import { UserWhereUniqueInput } from "../user/UserWhereUniqueInput";

export type SpaceCreateInput = {
  advertisments?: AdvertismentCreateNestedManyWithoutSpacesInput;
  availability?: InputJsonValue;
  bookingFee?: string | null;
  bookings?: BookingCreateNestedManyWithoutSpacesInput;
  bookingStage?: string | null;
  country?: string | null;
  county?: string | null;
  description?: string | null;
  dimensions: string;
  distanceToGround?: string | null;
  facingRoad?: boolean | null;
  farthestVisibility?: string | null;
  isOccupied: boolean;
  landmark?: string | null;
  legalDocs?: InputJsonValue;
  location?: string | null;
  maintenanceCharge?: string | null;
  maintenanceInterval?: string | null;
  minBookingPeriod?: string | null;
  ownerId?: string | null;
  photos?: InputJsonValue;
  price?: number | null;
  pricingPeriod?: string | null;
  ratings?: RatingCreateNestedManyWithoutSpacesInput;
  showPriceAs?: string | null;
  spaceContact?: string | null;
  spaceFeatures?: InputJsonValue;
  spaceId: string;
  spaceRestrictions?: string | null;
  spaceTitle?: string | null;
  spaceType?: string | null;
  status: string;
  user?: UserWhereUniqueInput | null;
  visibleAtNight?: boolean | null;
};
