import { SortOrder } from "../../util/SortOrder";

export type SpaceOrderByInput = {
  availability?: SortOrder;
  bookingFee?: SortOrder;
  country?: SortOrder;
  county?: SortOrder;
  createdAt?: SortOrder;
  description?: SortOrder;
  dimensions?: SortOrder;
  distanceToGround?: SortOrder;
  facingRoad?: SortOrder;
  farthestVisibility?: SortOrder;
  id?: SortOrder;
  landmark?: SortOrder;
  legalDocs?: SortOrder;
  location?: SortOrder;
  maintenanceCharge?: SortOrder;
  maintenanceInterval?: SortOrder;
  minListingPeriod?: SortOrder;
  ownerId?: SortOrder;
  photos?: SortOrder;
  price?: SortOrder;
  pricingPeriod?: SortOrder;
  showPriceAs?: SortOrder;
  spaceContact?: SortOrder;
  spaceFeatures?: SortOrder;
  spaceId?: SortOrder;
  spaceRestrictions?: SortOrder;
  spaceTitle?: SortOrder;
  spaceType?: SortOrder;
  updatedAt?: SortOrder;
  userId?: SortOrder;
  visibleAtNight?: SortOrder;
};
