import { AdvertismentUpdateManyWithoutSpacesInput } from "./AdvertismentUpdateManyWithoutSpacesInput";
import { InputJsonValue } from "../../types";
import { BookingUpdateManyWithoutSpacesInput } from "./BookingUpdateManyWithoutSpacesInput";
import { RatingUpdateManyWithoutSpacesInput } from "./RatingUpdateManyWithoutSpacesInput";
import { UserWhereUniqueInput } from "../user/UserWhereUniqueInput";

export type SpaceUpdateInput = {
  advertisments?: AdvertismentUpdateManyWithoutSpacesInput;
  availability?: InputJsonValue;
  bookingFee?: string | null;
  bookings?: BookingUpdateManyWithoutSpacesInput;
  country?: string | null;
  county?: string | null;
  description?: string | null;
  dimensions?: string;
  distanceToGround?: string | null;
  facingRoad?: boolean | null;
  farthestVisibility?: string | null;
  landmark?: string | null;
  legalDocs?: InputJsonValue;
  location?: string | null;
  maintenanceCharge?: string | null;
  maintenanceInterval?: string | null;
  minBookingPeriod?: string | null;
  ownerId?: string | null;
  photos?: InputJsonValue;
  price?: number | null;
  pricingPeriod?: string | null;
  ratings?: RatingUpdateManyWithoutSpacesInput;
  showPriceAs?: string | null;
  spaceContact?: string | null;
  spaceFeatures?: InputJsonValue;
  spaceId?: string;
  spaceRestrictions?: string | null;
  spaceTitle?: string | null;
  spaceType?: string | null;
  user?: UserWhereUniqueInput | null;
  visibleAtNight?: boolean | null;
};
